In [2]:
import cv2
import numpy as np

In [3]:
img = cv2.imread(filename='kart.png')
cv2.imshow(winname='Orginal', mat=img)
cv2.waitKey(0)

-1

In [4]:
# Resmin yeni boyutu
width = 400
height = 500

In [5]:
# pts1: Resimdeki kartın orjinal köşe indexleri
# pts2: Resimdeki kartın döndürülmüş halinin indexleri
pts1 = np.float32([[230, 1], [1, 472], [540, 150], [338, 617]])
pts2 = np.float32([[10, 10], [10, height], [width, 10], [width, height]])

In [6]:
matrix = cv2.getPerspectiveTransform(src=pts1, dst=pts2)
print(matrix)

[[ 9.62371479e-01  4.69296694e-01 -2.12098913e+02]
 [-4.21612535e-01  8.75392393e-01  1.05811315e+02]
 [-1.23898125e-04  7.89697479e-05  1.00000000e+00]]


In [7]:
# Dönüştürülmüş Resim
imgOutput = cv2.warpPerspective(src=img, M=matrix, dsize=(width, height))
cv2.imshow(winname='Donusturulmus Resim', mat=imgOutput)
cv2.waitKey(0)

-1

## cv2.getPerspectiveTransform(src, dst)
### src: Dönüştürme yapılacak noktaların koordinatlarını içeren Numpy dizisi. Dizinin şekli (4, 2) olmalıdır, yani dört noktanın (x,y) koordinatlarını içermelidir.
### dst: İdeal olarak dönüştürme sonucunda elde edilmek istenen noktaların koordinatlarını içeren Numpy dizisi. Dizinin şekli (4,2) olmalıdır, yani dört noktanın (x,y) koordinatlarını içermelidir.

## cv2.warpPerspective(src, M, dsize, flags, borderMode, borderValue)
### src: Dönüştürülecek görüntü. Numpy dizisi olarak temsil edilir.
### M: Dönüşüm matrisi. Dönüştürme matrisi, cv2.getPerspectiveTransform() fonksiyonuyla elde edilir.
### dsize: Çıktı görüntüsünün boyutu. Tuple olarak (genişlik, yükseklik) şeklinde belirtilir.
### flags: Dönüşüm yöntemini belirten bir bayrak. Varsayılan olarak cv2.INTER_LINEAR olarak ayarlanabilir.
### borderMode: Kenar piksellerinin nasıl işleneceğini belirten bir bayrak. Varsayılan olarak cv2.BORDER_CONSTANT ise kenar piksellerinin değeri. Varsayılan olarak 0 olarak ayarlanabilir.

In [9]:
width = 500
height = 600

pts1 = np.float32([[230, 1], [1, 472], [540, 150], [338, 617]])
pts2 = np.float32([[20, 20], [20, height-50], [width-50, 20], [width-50, height-50]])

matrix = cv2.getPerspectiveTransform(src=pts1, dst=pts2)
imgOutput2 = cv2.warpPerspective(src=img, M=matrix, dsize=(width, height))
cv2.imshow(winname='Practice1', mat=imgOutput2)
cv2.waitKey(0)

-1

In [10]:
img.shape

(620, 544, 3)

In [11]:
width = 544
height = 620

pts1 = np.float32([[230, 1], [1, 472], [540, 150], [338, 617]])
pts2 = np.float32([[20, 20], [20, height-30], [width-30, 20], [width-30, height-30]])

matrix = cv2.getPerspectiveTransform(src=pts1, dst=pts2)
imgOutput3 = cv2.warpPerspective(src=img, M=matrix, dsize=(width, height))
cv2.imshow(winname='Practice2', mat=imgOutput3)
cv2.waitKey(0)

-1